### ISSUE TITLE
Cannot dump all content of file to localfile

### ISSUE THREAD

**Issue by ToubieObie** [eduardok/libsmbclient-php#71] opened 2020-04-14 10:01 UTC
Hello,

I'm trying to copy files from a SMB share to a Linux host.
It is working so far verry good.

Code:
`# Open file on server`
`$file = smbclient_open($state, 'smb://'.$remotePath."/".$smb[$i+2], 'r');`
`while (true) {`
`       $data = smbclient_read($state, $file, 100000);`
`	if ($data === false || strlen($data) === 0) {`
`	  break;`
`	}`
`	#write content to local file`
`	file_put_contents($folder.$vendor."/".$invoicenrpath."/".$smb[$i+2], $data);`
`}`

My problem is when the file is big ( I think more than the 100000 bytes) the file is not fully streamed to the local file.

is there an other way to copy a file from SMB share to local linux host?

Best regards
Tobias

**Comment by remicollet** [comment] 2020-04-14 10:05
`copy("smb://....", "file://...");`

**Comment by ToubieObie** [comment] 2020-04-14 10:32
unfortunately it is not working...
I also tried to open the file before...
`Warning: copy(smb://...): failed to open stream: operation failed`

**Comment by eduardok** [comment] 2020-04-30 04:00
Isn't it because of SElinux or AppArmor perhaps?

**Comment by remicollet** [comment] 2020-09-01 08:45
@ToubieObie can not reproduce, can copy using smbclient_read or streams big file.

But you example is wrong
```
-  file_put_contents($folder.$vendor."/".$invoicenrpath."/".$smb[$i+2], $data);
+  file_put_contents($folder.$vendor."/".$invoicenrpath."/".$smb[$i+2], $data, FILE_APPEND);
```

Else, only the lastest chunk will be in the destination file.

See flag parameter of [file_put_contents](https://www.php.net/manual/en/function.file-put-contents.php)

**Comment by eduardok** [comment] 2021-09-10 17:56
> is there an other way to copy a file from SMB share to local linux host?

Yes, use: `smbclient //server/share -U username`

I'm closing until someone can reproduce this issue.

**Closed by eduardok** 2021-09-10 17:56 UTC
